import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]
[window]
padding.x = 30
padding.y = 40
dimensions = { columns = 82, lines = 22}
position = { x = 300, y = 300 }
decorations = "Buttonless"
option_as_alt = "Both"
startup_mode = "SimpleFullScreen"
title = "terminal"

[font]
size = 26.00
normal = { family = "ComicShannsMono Nerd Font", style = "Regular" }
bold = { family = "ComicShannsMono Nerd Font", style = "Bold" }
italic = { family = "ComicShannsMono Nerd Font", style = "Italic" }
